list(scenario1 = list(scenario = "scenario1", source_basename = "Sim_MEC_Cox_landmark_feature.R",
    source_sha256 = "c997ff5d163b4d7fbde848deabbfe004bf4480ac44062803a1ea317d04d8c17d",
    engine_basename = "scenario1_functions.R", engine_sha256 = "a2ac258db9d4498fad717eab3c57d427aab55bea44337f4d171cedff4031567d",
    function_count = 40L, function_names = c("expit", "clip01",
    "round_numeric_df", "solve_safe", "jacobian_fd", "make_stratified_folds",
    "source_score", "sample_source_covariates", "domain_shift",
    "prognostic_lp", "weibull_time", "generate_observed_data",
    "make_att_ipw_data_glm", "att_weights_from_gamma", "cox_score_eta_fixed_weight",
    "manual_linwei_se", "fit_unweighted_cox", "fit_att_ipw_naive_linwei_shu",
    ".to_matrix", ".bregman_family", ".weight_diag", "calibrate_weights_bregman_from_design_return",
    "make_balanced_tuning_indices", "make_stratified_train_valid_split",
    "binary_logloss", "safe_metric_min", "safe_metric_max", "tune_ps_ml",
    "tune_rsf_survival", "estimate_ps_ml", "fit_att_ipw_linwei_ml",
    "choose_landmark_times", "predict_survival_cox_train", "predict_survival_rsf_train",
    "estimate_mec_nuisance", "fit_mec_cox", "compute_true_att_target",
    "empty_row", "fit_one_rep", "required_worker_packages"),
    extracted_on = "2026-10-09", calculation_note = "The BART study conversion uses latent means and a range heuristic; its probit branch adds binaryOffset to values that already include it in dbarts. This differs from the posterior mean probability. RSF tuning uses max(C, 1-C)."),
    scenario2 = list(scenario = "scenario2", source_basename = "Sim_MEC_Cox_landmark_feature_two_OR.R",
        source_sha256 = "f1ea6ce94abe51057a045604a55c3d54a4d2b4ac30b1f839a281448024ff4055",
        engine_basename = "scenario2_functions.R", engine_sha256 = "f7da734d99eeb6e3d9c20914d63f3a9cd3cdfaf28318128ad73d76c9778a99a3",
        function_count = 40L, function_names = c("expit", "clip01",
        "round_numeric_df", "solve_safe", "jacobian_fd", "make_stratified_folds",
        "source_score", "sample_source_covariates", "domain_shift",
        "prognostic_lp", "weibull_time", "generate_observed_data",
        "make_att_ipw_data_glm", "att_weights_from_gamma", "cox_score_eta_fixed_weight",
        "manual_linwei_se", "fit_unweighted_cox", "fit_att_ipw_naive_linwei_shu",
        ".to_matrix", ".bregman_family", ".weight_diag", "calibrate_weights_bregman_from_design_return",
        "make_balanced_tuning_indices", "make_stratified_train_valid_split",
        "binary_logloss", "safe_metric_min", "safe_metric_max",
        "tune_ps_ml", "tune_rsf_survival", "estimate_ps_ml",
        "fit_att_ipw_linwei_ml", "choose_landmark_times", "predict_survival_cox_train",
        "predict_survival_rsf_train", "estimate_mec_nuisance",
        "fit_mec_cox", "compute_true_att_target", "empty_row",
        "fit_one_rep", "required_worker_packages"), extracted_on = "2026-10-09",
        calculation_note = "The BART study conversion uses latent means and a range heuristic; its probit branch adds binaryOffset to values that already include it in dbarts. This differs from the posterior mean probability. RSF tuning uses max(C, 1-C)."))
