#' Synthetic external-control example
#'
#' A simulated cohort of 160 target/trial patients and 320 external-control
#' patients. All records are synthetic and are used only for illustrating the
#' package interface. `source = 1` identifies the target/trial cohort;
#' `source = 0` identifies external controls. `event = 1` means death was
#' observed, and times are measured in months.
#'
#' @format A data frame with 480 rows and six columns: `time`, `event`,
#'   `source`, `age`, `sex`, and `marker`.
#' @source Generated by `data-raw/create_example_data.R`.
#' @usage data(example_external_controls)
"example_external_controls"
